### ISSUE TITLE
[UI] As a user I can select Drum mode or Synth mode

### ISSUE THREAD

**Issue by malparty** [malparty/nimbleat#6]
## Acceptance Criteria

- Add 2 buttons labeled `Drums`  and `Synth` respectively
- The drum button is preselected on page load
- Add a javascript variable `currentPadMode` (in the same class as the `playPad` function) to hold the current selection
- When a user clicks on a button, it deselects the other button and updates the `currentPadMode` variable

**Comment by markgravity** [comment]
Already done at https://github.com/malparty/nimbleat/pull/15
